name: Build and Publish
on:
  pull_request:
    branches:
      - "main"
permissions:
  contents: read
  id-token: write  # Required for publishing to PyPI
jobs:
  publish_linux:
    runs-on:
      - ubuntu-latest
    defaults:
      run:
        shell: bash
    environment:
      name: default
      url: https://pypi.org/p/byoconfig
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[development]
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.12.3
